### ISSUE TITLE
Node.js 16 is deprecated on GitHub Actions

### ISSUE THREAD

**Issue by janisozaur** [proudust/gh-describe#90]
Using
```
      - name: Git describe for shallow checkout
        id: ghd
        uses: proudust/gh-describe@v1
```
on GitHub Actions results in deprecation warning:

> Node.js 16 actions are deprecated. Please update the following actions to use Node.js 20: proudust/gh-describe@v1. For more information see: https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/.

**Comment by proudust** [comment]
Thanks for sending the [pull request](https://github.com/proudust/gh-describe/pull/91)!
We're releasing this fix as `v2` for those using Self-hosted Runners.
Please update the OpenRCT PR accordingly.

**Comment by proudust** [comment]
@janisozaur Sorry for the wait, now available `proudust/gh-describe@v2`!
